project:
  type: website

website:
  title: "Data Analytics in Healthcare"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu: 
          - text: "1. Introduction"
            href: "Hands-on_Ex/Hands-on_Ex01/Introduction.html"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    warning: false

editor: visual

