project:
  type: website

website:
  title: "Data Analytics in Healthcare"
  navbar:
    left:
      - text: "Hands-on Exercises"
      menu: 
         - href: Hands-on_Ex/Hands-on_Ex01/Introduction.qmd
         text: "1. Introduction"
         

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

